18:44:02.40 [WARN] File watcher exiting with: The watcher was shut down.
18:44:02.42 [31m[ERROR][0m 1 Exception encountered:

Engine traceback:
  in `package` goal

ResolveError: The file or directory 'function' does not exist on disk in the workspace, so the address 'function:cloud_function' from CLI arguments cannot be resolved.

